### ISSUE TITLE
Import js data as an external for pug

### ISSUE THREAD

**Issue by sananes** [aderaaij/totallystatical#6]
So, I was wondering. I've managed to add a new directory to templates called `/templates/data/`. Inside `data` folder, I've included an `index.js` file and `site.js`, just as an example. Anyway, I've managed to module export the data and then import it into the main `script.js` as `import data from ../data;`, then console logged some of the data I added and works great!

My issue is I would love to replace most of the variables from within pug files to basically reply on the data files as an external resource. Easier to manage a bunch of variables. Unfortunately, even though the data is accessible via the console I am not able to incorporate it in the pug files?

As another example in `index.pug`

```
head
  title #{site.title}
``` 
Pulling the data from `data/site.js` that has been compiled with `script.js`
```
module.exports = {
"title": "Homepage";
}
```

Do you have any idea how this can be achieved correctly, without running into any build issues.

Thanks in advance and I hope I made sense.

**Comment by aderaaij** [comment]
Ah that's interesting! I've never tried approaching it this way. So if I understand it right you want to have global data files that contain variables, etc so you could share those between Javascript AND pug files? Or do you just want a data file for the pug files? Because in the latter case, you could use `gulp-data` to make data from specific files or files within a folder available to pug. 

To get JS data directly though, is a bit trickier I believe. I've yet to try this, but I saw some interesting threads about it on the pug github:

https://github.com/pugjs/pug/issues/2758
https://github.com/pugjs/pug/issues/2604

Is there something of help in one of these threads?

**Comment by sananes** [comment]
@aderaaij thanks again for being so helpful! 

> So if I understand it right you want to have global data files that contain variables, etc so you could share those between Javascript AND pug files?

☝️ Yes this exactly! 

Just to give you a better idea of this being incorporated https://github.com/corygibbons/kita. This guy has done a great job using just `.js` files, but I just can't understand how he's got it to work like he has.

**Comment by aderaaij** [comment]
Oh that's a nice and clean generator! Everything done with NPM scripts. I like it! You probably already know that theses lines are the magic  
```
"watch:html": "pug -O src/data/index.js src/pug/*.pug --out dist -w -P",
"watch:css": "postcss src/css/index.css -o dist/css/style.css -w",
"watch:data": "onchange 'src/data/**/*.js' -- npm run build:html",
```
I need to have a look though!

**Comment by aderaaij** [comment]
Ah it seems you can just add the data through `gulp-data` or locales in the `gulpfile.js/tasks/template.js` file. I'll see if I can make an example!

**Comment by sananes** [comment]
If you could give me an example that would be fantastic! Again, thank you so much!

**Comment by aderaaij** [comment]
It'll probably be tomorrow, if it's as easy as I think it is, haha. Might be more difficult. Checkout https://tusharghate.com/rendering-pug-templates-with-multiple-data-files in the meanwhile. I think it's something like that which needs to be done! 

On a sidenote, I really like the Kita setup with no Gulp and just NPM scripts. I'm just afraid it'll get difficult to handle all the scripts with image processing, svg sprites, etc. 
I might still try though!

**Comment by sananes** [comment]
Haha yeah, no problem @aderaaij! Again thank you! So I initially actually went through that tutorial, but just couldn't get it to work. I kept getting an error saying:

```
WARNING!!
Passing multiple arguments is deprecated! Pass an options object instead.
```

I've been trying to figure out how to pass an object through instead.

**Comment by sananes** [comment]
> On a sidenote, I really like the Kita setup with no Gulp and just NPM scripts. I'm just afraid it'll get difficult to handle all the scripts with image processing, svg sprites, etc.
I might still try though!

Yeah I see what you're saying. You could just create some sort of hybrid that uses both methods 😃

**Comment by aderaaij** [comment]
Okay I've been having a quick go at this, but haven't gotten it to work with regular JS files yet. With a JSON file it's really straight forward. Add 

`.pipe(plugins.data(file => JSON.parse(fs.readFileSync('./app/src/data/test.json'))))` 

above `.pipe(plugins.pug({ pretty: true }))` and you're good. Just JS seems to be a different beast though, which I have yet to understand because it's seems so simple if you just use `pug-cli`. To be continued.  (oh also, I noticed that the `watch` command hangs when pug throws an error, I'll fix that in a release today).

**Comment by aderaaij** [comment]
Okay I had another stab at it and got it working in a minute by just replacing the `JSON.parse`, etc. with `require('../../app/src/data/index.js')` and it's working. Checkout the example at https://github.com/aderaaij/totallystatical/tree/data.

When I have some time I'll think about an implementation for this in the main branch. I think it might be a very useful addition. Of course I'll need to implement it in a way that it never gets in the way, and I'm wondering if in general, JSON files don't make more sense? A lot of data comes in JSON format anyhow and you could also use it in Javascript.

**Comment by sananes** [comment]
You my friend are an absolute gem! Thank you so much for helping me out with this. That totally worked, can't believe I didn't think to do that.. I will be contributing to this project for sure. I have a few nifty things which I feel would help loads with this repo. You've done a great job on this repo and I love it! Great job my man. I'll keep you updated!

**Comment by aderaaij** [comment]
I just saw that I didn't yet uploaded the changes to the data branch, I've done it now and you can see what I changed. I still need to figure some things out with caching and stuff. I now pull the data directly from the `data/site.js` file instead of the `data/index.js` because otherwise the changes to the data will not rebuild the templates. That'll probably be fixable. I've also added a watch task that rebuilds the template on data changes. You can find those here - https://github.com/aderaaij/totallystatical/blob/data/gulpfile.js/tasks/watch.js
and the changes to the template task here: 
https://github.com/aderaaij/totallystatical/blob/data/gulpfile.js/tasks/templates.js

And yay! Glad I could help, and it's fun to finally collaborate on this project a bit. Thanks again for the kind words, and also some extra motivation for this project. I'm definitely looking forward to your contributions (no pressure though! haha).
